spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update #create-drop #om man vill droppa
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/journal_db
    username: postgres
    password: password
